
services:
  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_ADMIN_PASSWORD=admin
    networks:
      - sonarqube-net

  sonarscanner:
    image: sonarsource/sonar-scanner-cli:latest
    depends_on:
      - sonarqube
    volumes:
      - .:/usr/src
    environment:
      - SONAR_HOST.url=http://localhost:9000
      - SONAR_TOKEN=sqp_0be85bab5fd1a5e0dd3c02e9ffbb413f9ee5228b
    networks:
      - sonarqube-net

networks:
  sonarqube-net: