name: ci-node-workflows
on:
  pull_request:
    branches:
      - develop

jobs:
  check-application:
    runs-on: ubuntu-latest

    #strategy:
    #  matrix:
    #    node-version: ['20.11.1']

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download the project code into the virtual machine
        uses: actions/checkout@v4
      - name: Configures the runtime environment with a specific version of Node.js
        uses: actions/setup-node@v4

        with:
          node-version: 20.11.1
          # node-version: ${{ matrix.node-version }} # only if strategy is being used

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true # push to dockerhub 
          tags: mrlucasapl/integracao-continua:latest # arrow the image name

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
      - name: install project dependencies
        run: npm ci
      - name: runs the tests
        run: npm test
      - name: runs the project build
        run: npm run build
